# Server Deployment Pod for K8s
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      component: server # server component
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: awakenedmind/multi-server
          ports: 
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD #name of env variable
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD # secret , key could be any 
              